#!/usr/bin/perl -w

=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=cut

use strict;
use Munin::Plugin::SNMP;

my $oid = "1.3.6.1.4.1.318.1.1.13.3.4.1.2.4.0";

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf") {
        print "require $oid [0-9]\n"; # Number
        exit 0;
}

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my ($host) = Munin::Plugin::SNMP->config_session();
        print "host_name $host\n" unless $host eq 'localhost';
        print "graph_title Air Flow
graph_args --base 1000 -l 0
graph_vlabel Air Flow(CFM)
graph_category Cooling
graph_info This graph shows the Air Flow
apc.label Air Flow
apc.info The Air Flow in Cubic Feet per Minute.
apc.draw AREA
";
        exit 0;
}

my $session = Munin::Plugin::SNMP->session( -translate => [ -timeticks => 0x0 ] );
my $val = $session->get_single("$oid") || 'T';

print "apc.value ", $val, "\n";
