#!/usr/bin/perl -w

=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=cut

use strict;
use Munin::Plugin::SNMP;

my $oid = ".1.3.6.1.4.1.318.1.1.13.3.4.1.2.6.0";

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf") {
        print "require $oid [0-9]\n"; # Number
        exit 0;
}

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my ($host) = Munin::Plugin::SNMP->config_session();
        print "host_name $host\n" unless $host eq 'localhost';
        print "graph_title Temperature
graph_args --base 1000 -l 0
graph_vlabel Temp(F)
graph_category Cooling
graph_info This graph shows the temperature
temp.label Temperature
temp.info The temperature in F.
temp.draw AREA
";
        exit 0;
}

my $session = Munin::Plugin::SNMP->session( -translate => [ -timeticks => 0x0 ] );
my $temp = $session->get_single("$oid") || 'T';


if ($temp ne 'T') {
    $temp /= 10; # Convert to degrees
}

print "temp.value ", $temp, "\n";
